In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/shrikant-temburwar/Wine-Quality-Dataset/master/winequality-red.csv",sep=';')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [4]:
# Let's check how many classes we have in our target column|

In [5]:
df['quality'].unique()

array([5, 6, 7, 4, 8, 3], dtype=int64)

In [6]:
# checking how many data we have in each class

In [7]:
df['quality'].value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [9]:
# checking the basic statistics of the data
df.describe().T

count       mean        std      min      25%  \
fixed acidity         1599.0   8.319637   1.741096  4.60000   7.1000   
volatile acidity      1599.0   0.527821   0.179060  0.12000   0.3900   
citric acid           1599.0   0.270976   0.194801  0.00000   0.0900   
residual sugar        1599.0   2.538806   1.409928  0.90000   1.9000   
chlorides             1599.0   0.087467   0.047065  0.01200   0.0700   
free sulfur dioxide   1599.0  15.874922  10.460157  1.00000   7.0000   
total sulfur dioxide  1599.0  46.467792  32.895324  6.00000  22.0000   
density               1599.0   0.996747   0.001887  0.99007   0.9956   
pH                    1599.0   3.311113   0.154386  2.74000   3.2100   
sulphates             1599.0   0.658149   0.169507  0.33000   0.5500   
alcohol               1599.0  10.422983   1.065668  8.40000   9.5000   
quality               1599.0   5.636023   0.807569  3.00000   5.0000   

                           50%        75%        max  
fixed acidity          7.90000   9.200000   15.90000  
volatile acidity       0.52000   0.640000    1.58000  
citric acid            0.26000   0.420000    1.00000  
residual sugar         2.20000   2.600000   15.50000  
chlorides              0.07900   0.090000    0.61100  
free sulfur dioxide   14.00000  21.000000   72.00000  
total sulfur dioxide  38.00000  62.000000  289.00000  
density                0.99675   0.997835    1.00369  
pH                     3.31000   3.400000    4.01000  
sulphates              0.62000   0.730000    2.00000  
alcohol               10.20000  11.100000   14.90000  
quality                6.00000   6.000000    8.00000

In [12]:
# let's check duplicated records in our data
df.duplicated().sum()

240

In [13]:
# Let's drop the duplicates
df = df.drop_duplicates()

In [14]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
5               7.4             0.660         0.00             1.8      0.075   
...             ...               ...          ...             ...        ...   
1593            6.8             0.620         0.08             1.9      0.068   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
5                    13.0                  40.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1593                 28.0                  38.0  0.99651  3.42       0.82   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
5         9.4        5  
...       ...      ...  
1593      9.5        6  
1594     10.5        5  
1595     11.2        6  
1597     10.2        5  
1598     11.0        6  

[1359 rows x 12 columns]

In [15]:
df.duplicated().sum()

0

In [17]:
# checking for null values
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [18]:
'''# Let's do standard scaling for our data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
'''
# for decision tree scaling is not required

"# Let's do standard scaling for our data\nfrom sklearn.preprocessing import StandardScaler\nscaler = StandardScaler()\n"

In [19]:
X = df.drop('quality',axis=1)
y = df['quality']

In [20]:
# train test split the data
from sklearn.model_selection import train_test_split, GridSearchCV
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [21]:
X_train

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
941             9.9              0.27         0.49             5.0      0.082   
525            10.4              0.64         0.24             2.8      0.105   
1015           10.5              0.39         0.46             2.2      0.075   
1487            6.0              0.64         0.05             1.9      0.066   
992             6.5              0.40         0.10             2.0      0.076   
...             ...               ...          ...             ...        ...   
1285           11.3              0.37         0.50             1.8      0.090   
1329            7.4              0.60         0.26             2.1      0.083   
1526            6.8              0.47         0.08             2.2      0.064   
1011            8.9              0.32         0.31             2.0      0.088   
1322            9.1              0.34         0.42             1.8      0.058   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
941                   9.0                  17.0  0.99484  3.19       0.52   
525                  29.0                  53.0  0.99980  3.24       0.67   
1015                 14.0                  27.0  0.99598  3.06       0.84   
1487                  9.0                  17.0  0.99496  3.52       0.78   
992                  30.0                  47.0  0.99554  3.36       0.48   
...                   ...                   ...      ...   ...        ...   
1285                 20.0                  47.0  0.99734  3.15       0.57   
1329                 17.0                  91.0  0.99616  3.29       0.56   
1526                 18.0                  38.0  0.99553  3.30       0.65   
1011                 12.0                  19.0  0.99570  3.17       0.55   
1322                  9.0                  18.0  0.99392  3.18       0.55   

      alcohol  
941      12.5  
525       9.9  
1015     11.4  
1487     10.6  
992       9.4  
...       ...  
1285     10.5  
1329      9.8  
1526      9.6  
1011     10.4  
1322     11.4  

[910 rows x 11 columns]

In [22]:
y_train

941     7
525     5
1015    6
1487    5
992     6
       ..
1285    5
1329    6
1526    6
1011    6
1322    5
Name: quality, Length: 910, dtype: int64

In [23]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()

In [24]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [27]:
y_pred = model.predict(X_test)
y_pred

array([4, 6, 6, 7, 4, 7, 6, 5, 7, 6, 6, 7, 5, 5, 6, 5, 5, 5, 5, 7, 5, 6,
       5, 5, 6, 5, 6, 5, 5, 6, 6, 7, 6, 6, 5, 6, 5, 6, 5, 7, 4, 5, 6, 5,
       6, 6, 5, 5, 4, 6, 6, 7, 5, 5, 6, 5, 4, 5, 6, 5, 5, 7, 5, 5, 5, 6,
       5, 6, 5, 7, 5, 8, 5, 6, 5, 5, 5, 5, 6, 5, 6, 5, 5, 6, 5, 7, 5, 5,
       6, 7, 6, 5, 5, 6, 6, 6, 4, 7, 6, 5, 5, 5, 6, 5, 5, 6, 7, 6, 5, 7,
       7, 6, 5, 5, 5, 6, 4, 5, 5, 6, 5, 5, 6, 6, 4, 5, 4, 6, 5, 5, 5, 5,
       6, 5, 5, 3, 7, 6, 6, 4, 4, 5, 7, 6, 7, 6, 6, 5, 6, 5, 4, 6, 5, 5,
       6, 7, 6, 5, 7, 7, 8, 5, 5, 6, 6, 6, 6, 5, 6, 7, 6, 6, 7, 6, 7, 7,
       5, 6, 5, 7, 5, 5, 4, 5, 5, 6, 5, 5, 4, 6, 3, 5, 6, 5, 6, 6, 6, 5,
       7, 6, 5, 5, 5, 7, 5, 7, 5, 6, 6, 6, 7, 6, 5, 5, 7, 5, 6, 7, 5, 6,
       6, 7, 6, 6, 4, 6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 7, 6, 5, 6, 5, 5, 5,
       6, 5, 7, 4, 5, 7, 5, 7, 6, 6, 7, 6, 6, 8, 5, 5, 6, 6, 7, 5, 5, 5,
       6, 6, 5, 6, 6, 6, 6, 5, 7, 5, 5, 5, 6, 6, 6, 4, 5, 7, 5, 7, 6, 6,
       5, 5, 5, 7, 5, 6, 4, 6, 6, 5, 5, 7, 4, 5, 4,

In [26]:
# Let's check the accuracy
from sklearn.metrics import accuracy_score

In [30]:
accuracy_score(y_test,y_pred)

0.47216035634743875

In [31]:
# let's check our model score
model.score(X_train,y_train)

1.0

In [32]:
# clearly it's overfitted

In [33]:
# let's do some hyperparameter tuning

In [34]:
grid_param = {
    'criterion':['gini','entropy'],
    'max_depth':range(2,32,1),
    'min_samples_leaf':range(1,10,1),
    'min_samples_split':range(2,10,1),
    'splitter':['best','random']
}

In [35]:
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(estimator=model,param_grid=grid_param,cv=5)

In [36]:
grid_search.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': range(2, 32),
                         'min_samples_leaf': range(1, 10),
                         'min_samples_split': range(2, 10),
                         'splitter': ['best', 'random']})

In [37]:
grid_search.best_params_

{'criterion': 'gini',
 'max_depth': 5,
 'min_samples_leaf': 6,
 'min_samples_split': 7,
 'splitter': 'random'}

In [38]:
# now let's train our model based on these hyperparameters

In [39]:
model_with_best_params = DecisionTreeClassifier(
    criterion='gini',
    max_depth=5,
    min_samples_leaf=6,
    min_samples_split=7,
    splitter='random'
)

In [40]:
model_with_best_params.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=5, min_samples_leaf=6, min_samples_split=7,
                       splitter='random')

In [41]:
model_with_best_params_pred = model_with_best_params.predict(X_test)
model_with_best_params_pred

array([5, 6, 6, 5, 6, 7, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 6, 5, 6, 6, 5, 5,
       5, 5, 6, 5, 6, 6, 5, 5, 6, 6, 6, 5, 5, 6, 5, 6, 5, 6, 4, 6, 5, 5,
       6, 6, 5, 5, 5, 6, 6, 6, 6, 5, 7, 5, 6, 5, 5, 6, 5, 6, 5, 7, 5, 6,
       5, 5, 5, 6, 5, 7, 5, 6, 6, 5, 5, 6, 5, 6, 6, 4, 5, 5, 5, 5, 5, 5,
       6, 6, 6, 5, 6, 6, 6, 6, 6, 7, 5, 5, 5, 5, 5, 6, 5, 5, 6, 6, 6, 6,
       6, 5, 5, 6, 5, 5, 5, 5, 5, 6, 6, 6, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5,
       6, 6, 5, 6, 6, 6, 6, 6, 5, 5, 6, 5, 6, 5, 6, 5, 6, 5, 5, 5, 5, 6,
       5, 6, 5, 5, 7, 7, 6, 6, 6, 6, 5, 6, 5, 5, 7, 6, 7, 5, 7, 6, 7, 6,
       6, 5, 5, 6, 5, 6, 5, 6, 5, 5, 6, 6, 5, 6, 6, 5, 6, 5, 5, 5, 6, 5,
       7, 6, 5, 6, 5, 7, 5, 5, 5, 5, 5, 6, 6, 7, 6, 5, 6, 5, 7, 5, 5, 5,
       5, 6, 6, 6, 5, 5, 6, 6, 6, 5, 6, 5, 5, 5, 6, 7, 6, 6, 5, 5, 5, 5,
       5, 5, 6, 5, 6, 6, 6, 7, 5, 5, 6, 6, 6, 5, 5, 5, 6, 5, 6, 5, 5, 6,
       6, 5, 5, 5, 6, 6, 6, 5, 7, 5, 5, 6, 5, 6, 5, 5, 5, 6, 6, 7, 6, 5,
       6, 5, 6, 6, 5, 6, 5, 5, 4, 5, 5, 7, 5, 5, 6,

In [42]:
accuracy_score(y_test,model_with_best_params_pred)

0.5501113585746102